# Generated by Django 5.1 on 2024-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('image', models.ImageField(upload_to='product_image/', verbose_name='Изображение продукта')),
            ],
            options={
                'verbose_name': 'Новые поступления',
                'verbose_name_plural': 'Новые поступления',
            },
        ),
    ]
