# Generated by Django 5.1 on 2024-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_birhday_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
