# Generated by Django 5.1 on 2024-08-29 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо написать в формате "+996*********".', regex='^\\+996\\d\\{9}$')], verbose_name='Номер телефона'),
        ),
    ]
